import Head from "next/head"
import {
  Button,
  Container,
  H1,
  Header,
  LinkButton,
  Paragraph,
  TextContainer,
} from "../components"
import { ContainerStyle } from "../components/container"
import { LinkButtonType } from "../components/linkButton/linkButton"
import { ParagraphStyle } from "../components/paragraph"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className="bg-[#FFB387] h-screen">
          <Container type={ContainerStyle.withPaddings}>
            <div className="flex flex-col px-4 pt-32 gap-y-7">
              <TextContainer>
                <H1 text="Everything you need to design" />
                <Paragraph
                  type={ParagraphStyle.heading}
                  text="Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio
              officia quos exercitationem quibusdam illo a nemo alias. At
              ducimus possimus asperiores omnis commodi dolores."
                />
              </TextContainer>
              <Button text="Get started for free" />
              <LinkButton type={LinkButtonType.anchor} text="See what's new" />
            </div>
          </Container>
        </div>
        <Container type={ContainerStyle.withPaddings}>
          <div className="w-full h-[220px] bg-orange-500 rounded-md -mt-40"></div>
        </Container>
      </main>

      <div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid dicta
          debitis enim ipsa natus et minima id incidunt expedita illo numquam
          reprehenderit tempore dignissimos voluptatum odit perspiciatis
          deserunt odio autem ut aperiam optio, iure maxime quis! Amet nihil
          vitae aspernatur nulla cumque dicta in dignissimos eos laborum at,
          dolore et consectetur ut, inventore, error aliquid. Voluptas fuga
          culpa error voluptatem. Blanditiis totam ea rerum, dicta ratione ipsam
          amet doloribus dolorem! Ducimus non ratione sed quo porro officiis
          atque illo, maiores perferendis quae ullam unde commodi, magni
          consequuntur blanditiis dicta? Necessitatibus dolore qui nesciunt
          repellendus doloremque eum. Obcaecati distinctio sed ipsam dolor a,
          inventore ducimus illum expedita doloribus, iusto sint perspiciatis
          quisquam repudiandae dolorum culpa delectus voluptas optio beatae
          corporis doloremque dolore. Fugit totam qui eos sapiente nihil ut,
          error magni quis eveniet dolorum dolores cupiditate neque corrupti,
          asperiores unde eum nobis, ab quos voluptatum quidem aliquam libero
          labore velit nostrum. Quo laboriosam voluptatum qui molestias dolor
          similique ex provident, itaque ad, corrupti maiores omnis hic tenetur
          esse numquam repellendus voluptatibus, sapiente expedita est! Aut ut
          cum eum obcaecati quidem cupiditate nesciunt! Amet obcaecati ad cumque
          dolores in consequatur, et, perspiciatis voluptates molestias fuga
          distinctio quis hic. Ducimus tempore necessitatibus nulla quo
          excepturi iste laboriosam officiis id laborum sint, et ipsum minima
          at! Dolorum porro eos modi error fugit! Fugiat illum sequi itaque
          pariatur eaque voluptates soluta, officia maiores nisi ab deleniti
          corporis optio neque nam unde dolor fuga in molestias possimus cum
          facere esse! Laudantium autem rerum dolore esse harum quae, cum
          delectus. Repudiandae dolore facere reprehenderit, neque officia
          quibusdam eveniet dolorem necessitatibus sint aperiam dignissimos,
          fuga id magnam commodi aut esse cum unde corporis excepturi saepe
          natus! Rerum beatae explicabo accusantium iure nisi aut voluptate
          dolore odit excepturi cumque saepe, quos necessitatibus id commodi ab.
          Officiis doloribus quod nostrum laborum sit dolore, pariatur incidunt,
          ratione sequi nam, dolorem voluptas corporis ducimus in quia nulla
          ullam aliquid eum ipsam. Error fugiat reprehenderit nulla molestiae
          perferendis nostrum modi omnis inventore, doloremque veritatis rerum
          impedit autem esse voluptas. Libero vero ad unde quibusdam expedita?
          Vel accusantium assumenda excepturi aliquam a adipisci magnam enim
          praesentium ea consequatur inventore veritatis, earum dignissimos
          eligendi pariatur esse voluptatem culpa ipsum ducimus ipsam id
          facilis. Officia esse ipsa vel, reiciendis asperiores nisi perferendis
          ab mollitia assumenda quia inventore, pariatur at facere omnis fugit
          officiis iusto rerum maxime laudantium voluptatibus tempore blanditiis
          nam temporibus. Aspernatur veniam est ex quam natus illum illo,
          delectus doloremque possimus voluptatibus, suscipit itaque libero
          dolorum nisi magni veritatis commodi cupiditate repudiandae aliquid!
          Consequatur impedit iusto voluptates iure incidunt tempore quibusdam
          dolorum magnam voluptatum, voluptatem corrupti velit veritatis, magni
          laboriosam excepturi porro facere, blanditiis culpa? Perspiciatis quod
          repellendus voluptates quasi distinctio, omnis fuga! Nam ipsam
          doloremque, sapiente accusantium asperiores labore amet enim debitis.
          Asperiores neque totam sapiente, voluptas ut distinctio repellendus
          cupiditate adipisci quis odit odio voluptatum quae dolor inventore
          consectetur. Dolor aspernatur libero provident reprehenderit ab
          nostrum aperiam deserunt id. Eaque necessitatibus neque magnam
          maiores. Modi ratione cupiditate quidem, dolorum tempore excepturi
          atque labore asperiores facere molestiae provident blanditiis porro
          harum distinctio, sunt consequuntur adipisci natus vero doloremque.
          Porro, exercitationem cumque corrupti illum totam eveniet perferendis
          corporis iusto. Sequi, corporis voluptates reiciendis tempora quaerat
          veniam at aspernatur in minima accusamus! Ducimus inventore temporibus
          recusandae ullam aut tempore doloremque provident mollitia aperiam, ex
          magni ad qui voluptates quibusdam sed dolore aspernatur eaque modi
          suscipit, quasi nobis, labore exercitationem quas nulla. Error impedit
          maiores voluptatibus explicabo quidem. Hic nostrum, officia error
          laborum ipsa, deleniti ratione earum dignissimos itaque, illo
          excepturi quae asperiores recusandae? Tempora consequuntur culpa
          soluta nulla velit praesentium consequatur, corrupti facere voluptas
          deserunt illum numquam! Maiores blanditiis fugit necessitatibus,
          molestiae quia atque nesciunt, dicta cum non ducimus doloremque
          excepturi illo. Aliquam qui repellat laudantium excepturi temporibus
          exercitationem optio, enim architecto ratione distinctio reiciendis
          corrupti iste quo ea recusandae repudiandae magnam odio, alias
          provident. Hic vel ullam distinctio consectetur tenetur molestiae,
          reiciendis error eum ut harum adipisci saepe amet, quidem omnis quasi
          corporis quis dolor quibusdam, explicabo ea eos. Quasi, ea sint? Earum
          eius nesciunt, veritatis vitae possimus laboriosam? Laboriosam
          quibusdam, dignissimos ad eligendi repellendus ab unde nesciunt totam
          eos cumque laudantium aut illum? Distinctio voluptate ad, qui illum in
          omnis odit reprehenderit nihil eveniet expedita quas sint consectetur
          provident optio illo eos praesentium ullam id delectus natus a! Natus,
          cupiditate minus dolorem quia accusantium quidem aspernatur, sit
          possimus quis ullam dicta atque unde, consequatur reprehenderit
          commodi ratione similique obcaecati? Iste, ratione, voluptatem maiores
          at exercitationem nam praesentium dicta quod incidunt repellendus
          minima porro unde veniam reiciendis libero deserunt, fuga sapiente est
          soluta distinctio quo rerum? Natus aspernatur officiis vel debitis,
          tenetur laudantium. Veritatis libero assumenda, rem alias beatae
          quibusdam debitis hic quis soluta aut vero laboriosam impedit esse,
          reprehenderit deleniti in temporibus architecto, maiores illum culpa
          adipisci sapiente dolorem facere? Recusandae quidem provident iste,
          necessitatibus asperiores dolorem, corporis alias at quia, nostrum sed
          minus error similique enim? Voluptatum nam temporibus voluptates, id
          nihil nemo cumque impedit beatae odit cum recusandae sed aliquid quod
          distinctio soluta dolores vero voluptate optio alias? Molestias,
          praesentium inventore itaque laboriosam veniam consequatur dolorem
          ipsum unde quasi et accusantium quas maxime sed ratione, at ut impedit
          exercitationem quisquam perspiciatis quia sit perferendis illum
          delectus architecto? Vitae repudiandae expedita quibusdam dolorem non
          doloribus, quos repellendus deserunt quod modi harum asperiores, ullam
          voluptate quaerat unde aliquid nostrum error rerum velit doloremque
          temporibus nulla excepturi provident voluptatem. Accusamus deleniti
          facilis accusantium necessitatibus?
        </p>
      </div>
    </div>
  )
}
